before:
  hooks:
    - go mod tidy

project_name: kapow

builds:
- id: kapow
  flags:
    - -trimpath
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
archives:
- format: binary
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-SHA512SUMS'
  algorithm: sha512
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - '^(chore|docs?|feat|fix|refactor|test|typo|wip)(\([^)]+\))?:'

dockers:
  - goos: linux
    goarch: amd64
    goarm: ''

    binaries:
      - kapow

    builds:
      - kapow

    image_templates:
      - "bbvalabsci/kapow:latest"
      - "bbvalabsci/kapow:{{ .Tag }}"
      - "bbvalabsci/kapow:v{{ .Major }}"

release:
  draft: true
  prerelease: auto
