before:
  hooks:
    - go mod tidy

project_name: kapow

builds:
- id: kapow
  flags:
    - -trimpath
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
archives:
- format: binary
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-SHA512SUMS'
  algorithm: sha512
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
signs:
  - artifacts: checksum
    signature: "${artifact}.GPG"
    args: ["--batch", "--local-user", "release-bot@kapow", "--output", "${signature}", "--armor", "--clear-sign", "${artifact}"]

dockers:
  - goos: linux
    goarch: amd64
    goarm: ''

    binaries:
      - kapow

    builds:
      - kapow

    image_templates:
      - "bbvalabsci/kapow:latest"
      - "bbvalabsci/kapow:{{ .Tag }}"
      - "bbvalabsci/kapow:{{ .Tag }}-{{ .Env.GO_VERSION }}"
      - "bbvalabsci/kapow:v{{ .Major }}"
