# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@protobufjs/aspromise-1.1.2" = {
      name = "_at_protobufjs_slash_aspromise";
      packageName = "@protobufjs/aspromise";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/aspromise/-/aspromise-1.1.2.tgz";
        sha1 = "9b8b0cc663d669a7d8f6f5d0893a14d348f30fbf";
      };
    };
    "@protobufjs/base64-1.1.2" = {
      name = "_at_protobufjs_slash_base64";
      packageName = "@protobufjs/base64";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/base64/-/base64-1.1.2.tgz";
        sha512 = "AZkcAA5vnN/v4PDqKyMR5lx7hZttPDgClv83E//FMNhR2TMcLUhfRUBHCmSl0oi9zMgDDqRUJkSxO3wm85+XLg==";
      };
    };
    "@protobufjs/codegen-2.0.4" = {
      name = "_at_protobufjs_slash_codegen";
      packageName = "@protobufjs/codegen";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/codegen/-/codegen-2.0.4.tgz";
        sha512 = "YyFaikqM5sH0ziFZCN3xDC7zeGaB/d0IUb9CATugHWbd1FRFwWwt4ld4OYMPWu5a3Xe01mGAULCdqhMlPl29Jg==";
      };
    };
    "@protobufjs/eventemitter-1.1.0" = {
      name = "_at_protobufjs_slash_eventemitter";
      packageName = "@protobufjs/eventemitter";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/eventemitter/-/eventemitter-1.1.0.tgz";
        sha1 = "355cbc98bafad5978f9ed095f397621f1d066b70";
      };
    };
    "@protobufjs/fetch-1.1.0" = {
      name = "_at_protobufjs_slash_fetch";
      packageName = "@protobufjs/fetch";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/fetch/-/fetch-1.1.0.tgz";
        sha1 = "ba99fb598614af65700c1619ff06d454b0d84c45";
      };
    };
    "@protobufjs/float-1.0.2" = {
      name = "_at_protobufjs_slash_float";
      packageName = "@protobufjs/float";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/float/-/float-1.0.2.tgz";
        sha1 = "5e9e1abdcb73fc0a7cb8b291df78c8cbd97b87d1";
      };
    };
    "@protobufjs/inquire-1.1.0" = {
      name = "_at_protobufjs_slash_inquire";
      packageName = "@protobufjs/inquire";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/inquire/-/inquire-1.1.0.tgz";
        sha1 = "ff200e3e7cf2429e2dcafc1140828e8cc638f089";
      };
    };
    "@protobufjs/path-1.1.2" = {
      name = "_at_protobufjs_slash_path";
      packageName = "@protobufjs/path";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/path/-/path-1.1.2.tgz";
        sha1 = "6cc2b20c5c9ad6ad0dccfd21ca7673d8d7fbf68d";
      };
    };
    "@protobufjs/pool-1.1.0" = {
      name = "_at_protobufjs_slash_pool";
      packageName = "@protobufjs/pool";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/pool/-/pool-1.1.0.tgz";
        sha1 = "09fd15f2d6d3abfa9b65bc366506d6ad7846ff54";
      };
    };
    "@protobufjs/utf8-1.1.0" = {
      name = "_at_protobufjs_slash_utf8";
      packageName = "@protobufjs/utf8";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/utf8/-/utf8-1.1.0.tgz";
        sha1 = "a777360b5b39a1a2e5106f8e858f2fd2d060c570";
      };
    };
    "@types/long-4.0.1" = {
      name = "_at_types_slash_long";
      packageName = "@types/long";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/long/-/long-4.0.1.tgz";
        sha512 = "5tXH6Bx/kNGd3MgffdmP4dy2Z+G4eaXw0SE81Tq3BNadtnMR5/ySMzX4SLEzHJzSmPNn4HIdpQsBvXMUykr58w==";
      };
    };
    "@types/node-13.13.40" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "13.13.40";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-13.13.40.tgz";
        sha512 = "eKaRo87lu1yAXrzEJl0zcJxfUMDT5/mZalFyOkT44rnQps41eS2pfWzbaulSPpQLFNy29bFqn+Y5lOTL8ATlEQ==";
      };
    };
    "@types/uuid-3.4.9" = {
      name = "_at_types_slash_uuid";
      packageName = "@types/uuid";
      version = "3.4.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/uuid/-/uuid-3.4.9.tgz";
        sha512 = "XDwyIlt/47l2kWLTzw/mtrpLdB+GPSskR2n/PIcPn+VYhVO77rGhRncIR5GPU0KRzXuqkDO+J5qqrG0Y8P6jzQ==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "commander-4.1.1" = {
      name = "commander";
      packageName = "commander";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-4.1.1.tgz";
        sha512 = "NOKm8xhkzAjzFx8B2v5OAHT+u5pRQc2UCa2Vq9jYL/31o2wi9mxBA7LIFs3sV5VSC49z6pEhfbMULvShKj26WA==";
      };
    };
    "commander-5.0.0" = {
      name = "commander";
      packageName = "commander";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-5.0.0.tgz";
        sha512 = "JrDGPAKjMGSP1G0DUoaceEJ3DZgAfr/q6X7FVk4+U5KxUSKviYGM2k6zWkfyyBHy5rAtzgYJFa1ro2O9PtoxwQ==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "core-js-3.6.4" = {
      name = "core-js";
      packageName = "core-js";
      version = "3.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-3.6.4.tgz";
        sha512 = "4paDGScNgZP2IXXilaffL9X7968RuvwlkK3xWtZRVqgd8SYNiVKRJvkFd1aqqEuPfN7E68ZHEp9hDj6lHj4Hyw==";
      };
    };
    "cucumber-messages-8.0.0" = {
      name = "cucumber-messages";
      packageName = "cucumber-messages";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cucumber-messages/-/cucumber-messages-8.0.0.tgz";
        sha512 = "lUnWRMjwA9+KhDec/5xRZV3Du67ISumHnVLywWQXyvzmc4P+Eqx8CoeQrBQoau3Pw1hs4kJLTDyV85hFBF00SQ==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "gherkin-9.0.0" = {
      name = "gherkin";
      packageName = "gherkin";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gherkin/-/gherkin-9.0.0.tgz";
        sha512 = "6xoAepoxo5vhkBXjB4RCfVnSKHu5z9SqXIQVUyj+Jw8BQX8odATlee5otXgdN8llZvyvHokuvNiBeB3naEnnIQ==";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "lodash-4.17.20" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.20.tgz";
        sha512 = "PlhdFcillOINfeV7Ni6oF1TAEayyZBoZ8bcshTHqOYJYlrqzRK5hagpagky5o4HfCzzd1TRkXPMFq6cKk9rGmA==";
      };
    };
    "long-4.0.0" = {
      name = "long";
      packageName = "long";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/long/-/long-4.0.0.tgz";
        sha512 = "XsP+KhQif4bjX1kbuSiySJFNAehNxgLb6hPRGJ9QsUr8ajHkuXGdrHmFUTUUXhDwVX2R5bY4JNZEwbUiMhV+MA==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "protobufjs-6.10.2" = {
      name = "protobufjs";
      packageName = "protobufjs";
      version = "6.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/protobufjs/-/protobufjs-6.10.2.tgz";
        sha512 = "27yj+04uF6ya9l+qfpH187aqEzfCF4+Uit0I9ZBQVqK09hk/SQzKa2MUqUpXaVa7LOFRg1TSSr3lVxGOk6c0SQ==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-support-0.5.19" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.19.tgz";
        sha512 = "Wonm7zOCIJzBGQdB+thsPar0kYuCIzYvxZwlBa87yi/Mdjv7Tip2cyVbLj5o0cFPN4EVkuTwb3GDDyUx2DGnGw==";
      };
    };
    "strip-json-comments-3.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.0.1.tgz";
        sha512 = "VTyMAUfdm047mwKl+u79WIdrZxtFtn+nBxHeb844XBQ9uMNTuTHdx2hc5RiAJYqwTj3wc/xe5HLSdJSkJ+WfZw==";
      };
    };
    "uuid-3.4.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz";
        sha512 = "HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
  };
in
{
  gherkin-lint = nodeEnv.buildNodePackage {
    name = "gherkin-lint";
    packageName = "gherkin-lint";
    version = "4.1.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/gherkin-lint/-/gherkin-lint-4.1.3.tgz";
      sha512 = "5oagKEUqPgwKkJGtlqshy8mWNpWBRIFDeex63BOPF3+yC2GOMjdyvAHTQfHhkDqgwEdOpda2F8yGe1EBj5/dgw==";
    };
    dependencies = [
      sources."@protobufjs/aspromise-1.1.2"
      sources."@protobufjs/base64-1.1.2"
      sources."@protobufjs/codegen-2.0.4"
      sources."@protobufjs/eventemitter-1.1.0"
      sources."@protobufjs/fetch-1.1.0"
      sources."@protobufjs/float-1.0.2"
      sources."@protobufjs/inquire-1.1.0"
      sources."@protobufjs/path-1.1.2"
      sources."@protobufjs/pool-1.1.0"
      sources."@protobufjs/utf8-1.1.0"
      sources."@types/long-4.0.1"
      sources."@types/node-13.13.40"
      sources."@types/uuid-3.4.9"
      sources."balanced-match-1.0.0"
      sources."brace-expansion-1.1.11"
      sources."buffer-from-1.1.1"
      sources."commander-5.0.0"
      sources."concat-map-0.0.1"
      sources."core-js-3.6.4"
      sources."cucumber-messages-8.0.0"
      sources."fs.realpath-1.0.0"
      (sources."gherkin-9.0.0" // {
        dependencies = [
          sources."commander-4.1.1"
        ];
      })
      sources."glob-7.1.6"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."lodash-4.17.20"
      sources."long-4.0.0"
      sources."minimatch-3.0.4"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."protobufjs-6.10.2"
      sources."source-map-0.6.1"
      sources."source-map-support-0.5.19"
      sources."strip-json-comments-3.0.1"
      sources."uuid-3.4.0"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A Gherkin linter/validator written in javascript";
      homepage = "https://github.com/vsiakka/gherkin-lint#readme";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}