name: Bump Go

on:
  schedule:
    - cron: 00 7 * * *
  push:
    branches:
      - master
jobs:
  bump-go:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone current repo
        uses: actions/checkout@v2

      - name: Ensure Go is up-to-date
        id: bump-go
        uses: BBVA/bump-go@main
        with:
          go-version-path: .github/versions/go

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Bump Go
          commit-message: Bump Go to version '${{ steps.bump-go.outputs.go-version }}'
          branch: bump-go/patch
